#新建用户中心database
create database oit_user_center charset utf8;
#新建用户中心table
DROP TABLE if exists oit_user;
CREATE TABLE oit_user(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    USERNAME VARCHAR(32)    COMMENT '用户名' ,
    PASSWORD VARCHAR(128)    COMMENT '密码' ,
    NAME VARCHAR(32)    COMMENT '姓名' ,
    MOBILE VARCHAR(32)    COMMENT '手机号' ,
    EMAIL VARCHAR(128)    COMMENT '电子邮箱' ,
    JOB_ID VARCHAR(32)    COMMENT '工号' ,
    JOB_TITLE VARCHAR(32)    COMMENT '职位' ,
    DEPARTMENT_ID INT    COMMENT '部门ID' ,
    DEPARTMENT VARCHAR(32)    COMMENT '部门' ,
    COMPANY_ID INT    COMMENT '公司ID' ,
    COMPANY VARCHAR(128)    COMMENT '公司' ,
    USER_TYPE CHAR(2)    COMMENT '用户类型' ,
    STATUS CHAR(1)    COMMENT '状态 1：启用；0：禁用' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户表 ';

ALTER TABLE oit_user COMMENT '用户表';
DROP TABLE if exists oit_organize;
CREATE TABLE oit_organize(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    NAME VARCHAR(32)    COMMENT '名称' ,
    PID INT    COMMENT '父节点 树形结构' ,
    RID INT    COMMENT '根节点 树形结构' ,
    SORT CHAR(2)    COMMENT '排序' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '组织结构表 ';

ALTER TABLE oit_organize COMMENT '组织结构表';
DROP TABLE if exists oit_user_organize_rel;
CREATE TABLE oit_user_organize_rel(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    USER_ID INT    COMMENT '用户ID' ,
    ORGANIZE_ID INT    COMMENT '组织ID' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户组织关系表 ';

ALTER TABLE oit_user_organize_rel COMMENT '用户组织关系表';
DROP TABLE if exists oit_app;
CREATE TABLE oit_app(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    APP_NAME VARCHAR(32)    COMMENT '应用名称' ,
    APP_KEY VARCHAR(32)    COMMENT 'APP_KEY' ,
    APP_SECRET VARCHAR(128)    COMMENT 'APP_SECRET' ,
    STATUS CHAR(1)    COMMENT '状态' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '系统应用表 ';

ALTER TABLE oit_app COMMENT '系统应用表';
DROP TABLE if exists oit_user_resource;
CREATE TABLE oit_user_resource(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    USER_ID INT    COMMENT '用户ID' ,
    RESOURCE_AUTH VARCHAR(3072)    COMMENT '资源权限' ,
    RESOURCE_TYPE CHAR(2)    COMMENT '资源类型 1：应用权限；2：数据权限；3：菜单权限；4：按钮权限；5：区域权限' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户资源表 ';

ALTER TABLE oit_user_resource COMMENT '用户资源表';
DROP TABLE if exists oit_role;
CREATE TABLE oit_role(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    ROLE_NAME VARCHAR(32)    COMMENT '角色名称' ,
    ROLE_CODE VARCHAR(32)    COMMENT '角色编码' ,
    ROLE_TYPE CHAR(2)    COMMENT '角色类型' ,
    COMPANY_ID INT    COMMENT '公司ID' ,
    COMPANY VARCHAR(128)    COMMENT '公司' ,
    STATUS CHAR(1)    COMMENT '状态' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '角色表 ';

ALTER TABLE oit_role COMMENT '角色表';
DROP TABLE if exists oit_role_resource;
CREATE TABLE oit_role_resource(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    ROLE_ID INT    COMMENT '角色ID' ,
    RESOURCE_AUTH VARCHAR(3072)    COMMENT '资源权限' ,
    RESOURCE_TYPE CHAR(2)    COMMENT '资源类型 1：菜单权限；2：按钮权限；' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '角色资源表 ';

ALTER TABLE oit_role_resource COMMENT '角色资源表';
DROP TABLE if exists oit_user_role_rel;
CREATE TABLE oit_user_role_rel(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    USER_ID INT    COMMENT '用户ID' ,
    ROLE_ID INT    COMMENT '角色ID' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户角色关系表 ';

ALTER TABLE oit_user_role_rel COMMENT '用户角色关系表';
DROP TABLE if exists oit_user_access;
CREATE TABLE oit_user_access(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    USER_ID INT    COMMENT '用户ID' ,
    USER_KEY VARCHAR(32)    COMMENT '用户标识' ,
    ACCESS_TOKEN VARCHAR(128)    COMMENT '授权码' ,
    PLATFORM_TYPE CHAR(2)    COMMENT '平台类型' ,
    KEY_EXPIRE INT    COMMENT '有效时间' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '平台用户授权登录表 ';

ALTER TABLE oit_user_access COMMENT '平台用户授权登录表';
DROP TABLE if exists oit_user_detail;
CREATE TABLE oit_user_detail(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    USER_ID INT    COMMENT '用户ID' ,
    SEX CHAR(1)    COMMENT '性别' ,
    CARD_NUM VARCHAR(32)    COMMENT '证件号码' ,
    CARD_TYPE CHAR(2)    COMMENT '证件类型' ,
    CONTACT_ADDRESS VARCHAR(128)    COMMENT '联系地址' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户扩展表 ';

ALTER TABLE oit_user_detail COMMENT '用户扩展表';
DROP TABLE if exists oit_resource;
CREATE TABLE oit_resource(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    APP_ID INT    COMMENT '应用ID' ,
    RESOURCE_NAME VARCHAR(32)    COMMENT '资源名称' ,
    RESOURCE_CODE VARCHAR(32)    COMMENT '资源编码' ,
    RESOURCE_TYPE CHAR(2)    COMMENT '资源类型' ,
    RESOURCE_PATH VARCHAR(1024)    COMMENT '资源路径' ,
    PID INT    COMMENT '父节点' ,
    SORT CHAR(2)    COMMENT '排序' ,
    STATUS CHAR(1)    COMMENT '状态' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    MODIFY_BY VARCHAR(32)    COMMENT '修改人' ,
    MODIFY_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
    PRIMARY KEY (ID)
) COMMENT = '页面资源表 ';

ALTER TABLE oit_resource COMMENT '页面资源表';

#用户中心索引
ALTER TABLE `oit_user` ADD UNIQUE (`username`);
ALTER TABLE `oit_app` ADD UNIQUE (`app_key`);
ALTER TABLE `oit_role` ADD UNIQUE (`role_code`);
ALTER TABLE `oit_resource` ADD UNIQUE (`resource_code`);
ALTER TABLE `oit_user_resource` CHANGE `resource_auth` `resource_auth` TEXT;